"use client";

import { useEffect, useMemo, useState } from "react";
import { AdminOpsHeader } from "@/components/admin-ops-header";
import { initialAdminOrders, readAdminOrders } from "@/lib/admin-orders";
import { fetchAdminOrdersFromApi } from "@/lib/admin-orders-api";

export default function AdminOverviewPage() {
  const [orders, setOrders] = useState(initialAdminOrders);
  useEffect(() => { if(process.env.NEXT_PUBLIC_SUPABASE_URL)void fetchAdminOrdersFromApi().then((data)=>{if(data)setOrders(data)});else setOrders(readAdminOrders()); }, []);
  const stats = useMemo(() => ({ active: orders.filter((item) => item.status === "قيد التنفيذ").length, waiting: orders.filter((item) => item.status === "بانتظار المستندات").length, done: orders.filter((item) => item.status === "مكتمل").length }), [orders]);
  return <main className="ops-shell" dir="rtl"><AdminOpsHeader active="dashboard" /><section className="overview-page"><div className="overview-heading"><div><p>الأحد، 22 يونيو</p><h1>صباح الخير، حسن</h1><span>هذه أهم الأعمال والمؤشرات التي تحتاجها اليوم.</span></div><a href="/admin">＋ طلب جديد</a></div><div className="overview-kpis"><article><i>▤</i><small>إجمالي الطلبات</small><strong>{orders.length}</strong><span>كل الطلبات المسجلة</span></article><article><i>⌁</i><small>قيد التنفيذ</small><strong>{stats.active}</strong><span>طلبات يعمل عليها الفريق</span></article><article className="warning"><i>!</i><small>بانتظار مستندات</small><strong>{stats.waiting}</strong><span>تحتاج تواصلًا مع العميل</span></article><article className="success"><i>✓</i><small>مكتملة</small><strong>{stats.done}</strong><span>تم إنجازها بنجاح</span></article></div><div className="overview-grid"><article className="overview-panel priority-panel"><header><div><h2>أولوية اليوم</h2><p>أعمال يوصى بالبدء بها الآن</p></div><a href="/admin/followups">عرض المتابعات ←</a></header>{orders.filter((item) => item.status !== "مكتمل").slice(0,4).map((order, index) => <div className="priority-row" key={order.id}><b>{index + 1}</b><div><strong>{order.nextAction}</strong><span>{order.client} · {order.id}</span></div><em className={index < 2 ? "urgent" : ""}>{index < 2 ? "عاجل" : order.nextActionAt}</em><a href="/admin">فتح ←</a></div>)}</article><aside className="overview-panel workload"><header><h2>عبء الفريق</h2><p>توزيع الطلبات النشطة</p></header>{["أحمد السبيعي", "سارة العتيبي", "نورة القحطاني"].map((name) => { const count = orders.filter((item) => item.assignee === name && item.status !== "مكتمل").length; return <div key={name}><span className="team-dot">{name.charAt(0)}</span><p><strong>{name}</strong><small>{count} طلبات نشطة</small></p><b style={{width:`${Math.max(18,count * 22)}%`}}></b><em>{count}</em></div>; })}</aside></div><div className="overview-actions"><a href="/admin"><span>▤</span><strong>إدارة الطلبات</strong><small>بحث وتحديث وإنشاء الطلبات</small></a><a href="/admin/clients"><span>♙</span><strong>ملفات العملاء</strong><small>الوصول لبيانات وطلبات العميل</small></a><a href="/admin/followups"><span>◷</span><strong>المتابعات</strong><small>الإجراءات والمواعيد القادمة</small></a><a href="/admin/services"><span>◇</span><strong>كتالوج الخدمات</strong><small>إدارة الخدمات والمتطلبات</small></a></div></section></main>;
}
